### ISSUE TITLE
Version for gulp

### ISSUE THREAD

**Issue by adamjw3** [MathiasPaumgarten/grunt-bake#100]
Not an issue but have used bake for ages and love it. new job uses gulp so looking for a version i can use with that. do you have one?

**Comment by MathiasPaumgarten** [comment]
I've thought about porting it a while ago. I never really got around to do it sadly. I don't think it would be way too much work, but essentially all file readings would have to be converted to streams. 

Personally, I don't even use **grunt-bake** much anymore. I mostly use [pug](https://github.com/pugjs/pug) these days. 

I don't think I can promise that a port will happen anytime soon (or ever) unless we find a volunteer to put some time into it.
