### ISSUE TITLE
<!--(bake remove when="")-->

### ISSUE THREAD

**Issue by ffraval** [MathiasPaumgarten/grunt-bake#22]
HI,

i'm now using bake for a big site project and i'm very pleased with your plugin. I use it in a specific way that allow me to have real semantic html files as input (partial) and real semantic html files as output.

I've got component files that are included in module files that are included in layout files. Every files are semantic and can be viewed in a browser as real html files. I'm using the IF statement to remove <!doctype> when the files are included and to let the <!doctype> when the files are just baked. 

<!doctype> . It's not a good usage but it work and all my files, src, output, baked, include, are semantic files and can be view in a browser as standalone files or included in another semantic file

I'm thinking that a <!doctype> could be a great feature to add to your plugin.

With this, it would be the only htlm recursive builder that could take semantic html files as input and deliver real semantic htlm file as output, included or baked. The purpose is to have an html builder that use html file syntax.

I've tried to make this possible but i'm an html/css guy not a javascript one :).

I hope i've been understandable ;).

thanks again for your great work on bake :).

**Comment by MathiasPaumgarten** [comment]
As I am reviewing some older issues. This has been open for a long time and not approved upon. I think I will close this feature task until it comes up again. I haven't heard of another person needing it.

Thanks everyone! If anyone is still in need for this, I am more than willing to revisit this.
