### ISSUE TITLE
Pass in parts of options.content as inline values

### ISSUE THREAD

**Issue by snorripall** [MathiasPaumgarten/grunt-bake#24]
It would be useful to pass in object from the options.content as inline values. 

If I pass this json in via the option.content ...

***myconfig.json***
```json
{
  "myobject": [
    {
      "title": "Git ate the last mint"
    },
    {
      "title": "Git explodes"
    },
    {
      "title": "Waiter says ..."
    }
  ]
}
```
... i can reference it in a _foreach loop.

**item.htm**

```html
<!--(bake-start _foreach="item:myobject")-->
<div class="item itmN">
  <h3>
    <a href="/url">{{item.title}}</a>
  </h3>
</div>
<!--(bake-end)-->
```
This is enough in most cases. But let's say you want to use a different set of data for the item.htm template there would need to be some way of passing in the object that should be used. 

```json
{
  "myobject": [
    {
      "title": "Git ate the last mint"
    },
    {
      "title": "Git explodes"
    },
    {
      "title": "Waiter says ..."
    }
  ], 
  "stars": [
    {
      "title": "Jupiter"
    },
    {
      "title": "Pluto. Yes Pluto."
    },
    {
      "title": "Mars"
    }
  ]
}
```

**itemlist.htm**
```html
<div class="items">
  <!--(bake item.htm @list="myobject" )-->
  <!--(bake item.htm @list="stars" )-->
</div>
```

**item.htm**

```html
<!--(bake-start _foreach="@list")-->
<div class="item itmN">
  <h3>
    <a href="/url">{{title}}</a>
  </h3>
</div>
<!--(bake-end)-->
```

Not sure about the @ sign, just used it to differentiate from a normal variable. 

Am I making any sense ?

**Comment by MathiasPaumgarten** [comment]
Closing this in favor for a newer issue that discusses the same: #41
