### ISSUE TITLE
Ability to use the inline _render flag with JS and Sass/CSS?

### ISSUE THREAD

**Issue by benfrain** [MathiasPaumgarten/grunt-bake#36]
I've been using Grunt on a daily basis for a good year or so now so firstly, thanks for the great plugin.

I have now reached a point on a project where I would like to facilitate some simple switching of logic across HTML, CSS and JS files. 

With grunt-bake, in HTML this is working well. I have this kind of thing in my Gruntfile:

```js
options: {
	process	: false,
	case1: true,
	case2: false
}
```

And I switch the values as needed. That way includes like this get switched on or off:

```html
<!--(bake /source/thing.html _render="case1")-->
```

However, I'd like to enjoy the same capability in Sass/CSS and JS files so that code can be switched on/off and included in the same manner (and crucially based upon the same flags in the Gruntfile).

For example, this syntax in JS/Sass:

```javascript
//  (bake-start _render="case1")
Case 1 specific code here
// (bake-end)
```

And this syntax in CSS:

```css
/* (bake-start _render="case1") */
Case 1 specific CSS here
/* (bake-end) */
```

Could grunt-bake be extended to facilitate this requirement? Or do you consider it out of scope?

**Comment by MathiasPaumgarten** [comment]
Hi. I'm trying to loop back to older tickets and see if they are still relevant. I think I will close this, as I have not spent any more time on this. Additionally, I am leaning more towards it being out of scope. I think there might be a use case for it, but it should most likely be built in a separate plugin.
