### ISSUE TITLE
Nested ifs and for-loops

### ISSUE THREAD

**Issue by shammar13** [MathiasPaumgarten/grunt-bake#37]
I've been trying to do some templating that leads to nested if-statements or if-statements nested in for-loops. Is there any chance that nested statements like that can be added to the library?

**Comment by Heydon** [comment]
Any movement on this? :-)

**Comment by MathiasPaumgarten** [comment]
Sorry. Nothing yet. :disappointed: 

PR welcome :wink:

**Comment by Heydon** [comment]
Ha! Sorry, no time either. Great plugin all the same. Thanks!

**Comment by domfee** [comment]
Hi @MathiasPaumgarten any news on this? Its a real sticking point for a project I'm working on.

**Comment by MathiasPaumgarten** [comment]
@domfee, thanks for the interest, I try to make more room for __grunt-bake__ but as of right now I haven't gotten around to this. Sorry to disappoint.

**Comment by MathiasPaumgarten** [comment]
However, you can use the `_if` statement and nest it, as long as it is not in the inline definition.

**Comment by bgottlob** [comment]
I'd like to be able to nest for loops for nested arrays in my JSON content file. Does anyone know how this might be implemented?

**Comment by MathiasPaumgarten** [comment]
Thanks to a big push of @david-zacharias, nested loops and nested ifs are not possible!

version `1.0.0`

**Comment by Heydon** [comment]
This is awesome news! Well done. To the Twitters>>>>

**Comment by Heydon** [comment]
https://twitter.com/heydonworks/status/676852175247679488
