### ISSUE TITLE
Getting data on key from array

### ISSUE THREAD

**Issue by danilvalov** [MathiasPaumgarten/grunt-bake#41]
Please, add support for getting data on key from array.

Example:

header.html:
```
<header>
  <ul class="menu">
    <!--(bake-start _foreach="menu:[page2,page3,page4]")
    <li class="menu__item">
      {{pages[menu].title}}
    </li>
    <!--(bake-end)
  </ul>
</header>
```

content.json:
```
{
  "pages": [
    "page1": {
      "title": "Page 1"
    },
    "page2": {
      "title": "Page 2"
    },
    "page3": {
      "title": "Page 3"
    },
    "page4": {
      "title": "Page 4"
    },
    "page5": {
      "title": "Page 5"
    }
  ]
}
```

**Comment by MathiasPaumgarten** [comment]
Hey there,

this has been requested a few times. It is definitely on my list. Thanks for using and the feedback.

**Comment by morkro** [comment]
Hey @MathiasPaumgarten,

how is your progress here? Is it possible to contribute? 
I really would like to have this feature and if somehow possible, I could also start developing it. 

What do you think? :grinning:

**Comment by MathiasPaumgarten** [comment]
Hi @morkro,

thanks for the interest. I am always open to contribution. I know I haven't spent much time on it, but if you are willing to give it a go, that'd be amazing. 

Should be fairly straight forward. I'd appreciate if you could keep my coding style up and write a few tests with your feature.

Let me know if you need anything from me.

**Comment by morkro** [comment]
Hey @MathiasPaumgarten,

sounds great! Of course I'll keep your coding style up and add tests. Anything else I should take care of?

I will start to tackle this in the next days and keep you posted :v:

**Comment by morkro** [comment]
@MathiasPaumgarten: just want to keep you up to date. Had almost zero time the last couple of days, but will start on the coming weekend.

**Comment by MathiasPaumgarten** [comment]
Sounds good. You know what they say: _"Fast is fine but accuracy is final. You must learn to be slow in a hurry"_

**Comment by david-zacharias** [comment]
Just an idea - how about extending `resolveName` slightly that it does a search for array notations and resolves keys before finally looking up the value? 

```JS
function resolveName( name, values ) {
	name = name.replace( /\[([^\]]+)\]/g, function( match, inner ) {
		return "." + resolveName( inner, values );
	});

	return mout.object.get( values, name ) || "";
}
```

**Comment by MathiasPaumgarten** [comment]
Actually, since it is using [`mout.object.get`](https://github.com/mout/mout/blob/v0.11.0/src/object/get.js#L11) it allows arrays, to a degree. The notation can not involve square brackets but if you write it with numbers and the dot notation it would work.

As an example:

```js
var object = { foo: [ { bar: true } ] };
console.log( object[ "foo" ][ "0" ][ "bar" ] ); // true
```

Probably has to do with arrays being objects as well, except the key names are numbers.

Not fully sure how that solves this problem, but wanted to through that out there. :smile:

**Comment by david-zacharias** [comment]
I think the behavior of `mout.object.get` and my addition together solve the request from @danilvalov and @morkro. Basically my addition rewrites the syntax *and* replaces variables used as keys the matching content from the json. `mout.object.get` then gets the data regardless of the keys type.

**Comment by MathiasPaumgarten** [comment]
I'd be down for a PR. If the tests check out :smile: 

@david-zacharias @morkro @danilvalov any takers?

**Comment by david-zacharias** [comment]
I can implement the changes next week. I think with #57 there is enough for code review this week :wink:

**Comment by morkro** [comment]
Great, thanks for doing this @david-zacharias! :clap: 
Unfortunately I haven't time for any spare time coding since then.

**Comment by MathiasPaumgarten** [comment]
I just merged a huge PR from @david-zacharias that propelled __grunt-bake__ forward quite a bit. If you guys would like to add this suggested fix from @david-zacharias as well, I'd gladly take in another PR. I'd copy it myself, but since it's David's code, I'd like for him to write a PR so he can collect the Github Karma, and shows up correctly in contributions :smile: 

Because you know, respect where respect is due.

**Comment by david-zacharias** [comment]
Hi all! I will create a PR today as I am going to fix another thing as well: The unwanted removal of `0` in `resolveNames()` as mentioned in #54.

**Comment by MathiasPaumgarten** [comment]
@danilvalov good news. Thanks to @david-zacharias (again!) your wish has been heard. :clap:

**Comment by danilvalov** [comment]
@MathiasPaumgarten It's really cool! I'm waiting for this! Thank you so much!
