### ISSUE TITLE
wrap includes?

### ISSUE THREAD

**Issue by cj** [MathiasPaumgarten/grunt-bake#42]
Is it possible to wrap includes?  Lets say you have something called layout.html:

```slim
doctype html
html
  head
    /!(bake includes/_head.html)
  body.index
    /! (bake includes/_header.html)
    .row-wrapper
      .outer-container
        #content
          /! (bake includes/_sidebar.html)
          main role="content" 
            {{block_content}}
```

Is it possible to do something like this?:

```slim
/! (bake start includes/layout.html)
  contents of your file.
/! (bake end)
```

**Comment by MathiasPaumgarten** [comment]
Hi there,

sorry I just saw this. I'm really sorry for the super delayed response. Sadly there isn't a feature like that in there, but it also seems that you might be using something like [Jade](http://jade-lang.com/) which allows for features like that. __Jade__ pretty much includes everything __grunt-bake__ does and much more.

**Comment by MathiasPaumgarten** [comment]
I think writing this `contents` feature, while very useful, is out of scope.
