### ISSUE TITLE
Multiple JSON Content Files for Multiple HTML Files

### ISSUE THREAD

**Issue by bgottlob** [MathiasPaumgarten/grunt-bake#45]
Is there any way to use multiple content JSON files with the bake task? I would like to have one JSON file per HTML file in my project if possible. I read issue #27 but I'm not sure if a solution for it has been implemented.

By the way, great job on this project!

**Comment by MathiasPaumgarten** [comment]
Hi there Brandon,

So if I understand your question correctly, you could use different bake tasks:

```js
bake: {
	home_bake: {
		options: {
			content: "test/content-home.json"
		},

		files: {
			"dest/home.html": "views/home.html"
		}
	},
	subsite: {
		options: {
			content: "test/content-subsite.json"
		},

		files: {
			"dest/subsite.html": "views/subsite.html"
		}
	},
}
```

Alternativly you could merge mutilple JSON files into one, first and then use this one JSON file to bake all your files. That would be  better solution if you want to share certain variables across multiple. 

This can't be done through __grunt-bake__ itself but I wrote a different task for something like that: [grunt-json-bake](https://github.com/MathiasPaumgarten/grunt-json-bake)

It would allow you to merge all the files into one JSON and then use that JSON. 

Let me know if I understood your question correctly.

**Comment by bgottlob** [comment]
Yes, you understood it correctly. It looks like this will do the trick for me, I'll try it out. Thanks!

**Comment by AdrianoCahete** [comment]
@MathiasPaumgarten I need to read package.json and another json file to the same template. It's possible?

Now, if i put the two entries, just the last work.

```
gh_api: {
  options: {
    basePath: 'src/template',
    content: function() {
      var file = 'src/data/githubapi.json';
      var content = grunt.file.readJSON(file);
      content['gh_api'] = grunt.config.get('gh_api');
        return content;
      }
   },
   files: {
     'release/index.html' : 'src/template/_index.html'
   }
 },

pkg: {
  options: {
    basePath: 'src/template',
    content: function() {
      var file = 'package.json';
      var content = grunt.file.readJSON(file);
        content['pkg'] = grunt.config.get('pkg');
        return content;
      }
    },
    files: {
      'release/index.html' : 'src/template/_index.html'
  }
}, 
```

`githubapi.json` is a json response to `https://api.github.com/users/AdrianoCahete`

**Comment by david-zacharias** [comment]
Hi @AdrianoCahete, you need to combine the data within the `content`-function. Otherwise the both tasks will create baked files, where the later one overwrites the first one.

Basically you have to do:
```JS
gh_api: {
  options: {
    basePath: 'src/template',
    content: function() {
      var file;
      var content = {};

      file = 'src/data/githubapi.json';
      content = grunt.file.readJSON(file);
      content['gh_api'] = grunt.config.get('gh_api');
        return content;
      }
      
      file = 'package.json';
      content = grunt.file.readJSON(file);
        content['pkg'] = grunt.config.get('pkg');
      }

      return content;
   }
}, 
```

A nicer version:
```JS
gh_api: {
  options: {
    basePath: 'src/template',
    content: function() {
      var files = [{
          path: 'src/data/githubapi.json',
          alias: 'gh_api'
        }, {
          path: 'package.json',
          alias: 'pkg'
        }];

      return files.reduce(function(content, file) {
        content[file.alias] = grunt.file.readJSON(file.path);
        return content;
      }, {});
    }
}, 
```

You can than access the variables in your template like `{{pkg.version}}`.

**Comment by AdrianoCahete** [comment]
Hi @david-zacharias ! Thanks for explanation... But i try this and don't work.

You can see my [gruntfile here](https://github.com/AdrianoCahete/Portfolio/blob/static-grunt/GruntFile.js).
This is a small project, you can get it and test too. The title needs to be in page title, links needs to be working (they are from package.json) and profile image needs to be working (it's from githubapi,json).
  
Now, none of theses are working. :(

**Comment by david-zacharias** [comment]
On a first quick glance I would say, your bake-task is missing a `files`-property, see [Bake overview](https://github.com/MathiasPaumgarten/grunt-bake#overview)

**Comment by AdrianoCahete** [comment]
> On a first quick glance I would say, your bake-task is missing a files-property, see Bake overview

Oh, it's true!
Probably i removed on copy/paste... So embarrassing.

Now works, thanks a lot! :)
