### ISSUE TITLE
Conditional Logic in the templates

### ISSUE THREAD

**Issue by musdy** [MathiasPaumgarten/grunt-bake#46]
Hello Mathias,

Do you consider adding if/else or any other conditional logic to bake? While using it, that is one of the things I find missing. 

Thanks.

- M

**Comment by MathiasPaumgarten** [comment]
Hi @musdy 

There is some sort of __if__ functionality in it as of right now. Described in the README right [here](https://github.com/MathiasPaumgarten/grunt-bake#if-statement)

Can you describe a scenario you'd like to see?

There is no else task so far. one would have to do a _if-not_

```html
<html>
    <body>
        <!--(bake includes/container.html _if="name")-->
        <!--(bake includes/login-panel.html _if="!name")-->
    </body>
</html>
```

**Comment by musdy** [comment]
Hey @MathiasPaumgarten ,

I am using Grunt bake in another project and realized that the thing that's missing is more logic on if:


<h1>Custom homepage text</h1>
 

Any way of doing something similar to this without polluting the bake file?

- M

**Comment by MathiasPaumgarten** [comment]
Hi @musdy 
thanks for the interest in __grunt-bake__. This is an interesting feature. I don't know how much time I have on my plate, but I try to squeeze it in, if I can find a nice clean way without breaking the API as it is. There might be a nice way in parsing the value within `_if="value"` where `value` represents a logic expression. 

Let me get backs to you about this. And of course, feel free to take a stab at a PR if you want to.

**Comment by MathiasPaumgarten** [comment]
Hey @musdy, I've added your feature request in version `0.3.16`. See this PR: #49

**Comment by musdy** [comment]
Thanks a lot man. This is great!
