### ISSUE TITLE
Question about parsing array

### ISSUE THREAD

**Issue by AdrianoCahete** [MathiasPaumgarten/grunt-bake#48]
I think it's a question not an issue.

I have a json with this data:
```
(...)
    "unique-colours": [
        "#749DCB",
        "#3C3C3C",
        "#E6EDF2",
        "#2C5078"
  },
(...)
```

In html i have 
```
<p>unique-colours {{unique-colours}}</p>
```

Which output:
```
unique-colours #749DCB,#3C3C3C,#E6EDF2,#2C5078
```

But i want to output to determined spaces.  Like this:
```
<p>color #749DCB</p>
<p>color #3C3C3C</p>
<p>color #E6EDF23C</p>
<p>color #2C50783C</p>
```

Can i do it? How?

**Comment by MathiasPaumgarten** [comment]
Hi there,

yep, there is a [`_foreach`](https://github.com/MathiasPaumgarten/grunt-bake#foreach-loop) loop built in:

```html
<!--(bake-start _foreach="colour:unique-colours")-->
    <p>{{colour}}</p>
<!--(bake-end)-->
```

This should do the trick. Hope that helps.

**Comment by AdrianoCahete** [comment]
Works like a charm! Thank you! :)
