### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by MathiasPaumgarten** [MathiasPaumgarten/grunt-bake#53]
Hey, @PaulHuizer @david-zacharias 

As you see I've added an [`contributors`](https://github.com/MathiasPaumgarten/grunt-bake/blob/master/package.json#L11) section into the `package.json`. I wasn't sure what you want in your fields as email address. Probably the same as your npm email, as it will link you that way, I think. 

Let me know what you want there as an email address, if you do want to be there at all.

**Comment by david-zacharias** [comment]
Hey and thanks! You can add my company email address zacharias@werk85.de

**Comment by MathiasPaumgarten** [comment]
I'm gonna close this for now. If you (@PaulHuizer) change your mind, comment and I'll gladly add you to the list.
