### ISSUE TITLE
Support for Meta-Information in foreach-loops

### ISSUE THREAD

**Issue by david-zacharias** [MathiasPaumgarten/grunt-bake#54]
Following problem: I want to create a [Bootstrap carousel](https://getbootstrap.com/javascript/#carousel). To make the carousel indicators work these need numeric ascending ids. Data for the carousel comes from a json file.

One solution could be to add the ids to the json, but that is unnecessary data-overhead (IMHO). So why not letting bake supply meta information about the loop like *current iteration number*, *is this the last iteration*, etc.

I came up with the following syntax, where bake injects variables composed of the variables key, an @-sign, and the information name.

```HTML
...
<!--(bake-start _foreach="slide:slides")-->
    <li data-slide-to="{{slide@index}}">...</li>
<!--(bake-end)-->
...
```

This way, we can have additional information in the template without having name conflicts. 

The extends to bake are pretty small, mainly some of these lines, where the `forEachValues` are processed.

```JS
forEachValues.forEach( function( value, index ) {
    values[ forEachName ] = value;
    // assign meta vars with information about current iteration
    values[ forEachName + "@index" ] = String( index );
    // ...
```
 I already made an implementation and will create a PR in some minutes. 

**Minor flaw**: The `String()`-casting. It's currently needed because otherwise `0` is not present in template because in `resolveName()` the `|| ""` kicks in and returns an emptry string instead of `0`.

Maybe this behavior can be changed together with #41

**Comment by MathiasPaumgarten** [comment]
Thanks to you that is now part of it as well.
