### ISSUE TITLE
Resolve also right part in validateIf()

### ISSUE THREAD

**Issue by david-zacharias** [MathiasPaumgarten/grunt-bake#55]
`validateIf()` currently only resolves the left part of an if-condition into the corresponding value. Especially when the meta information for loops #54 (and more recursion support :yum:) make their way into bake, it could be nice to evaluate variable against variable.

As may expected, I have implemented support for this (unfortunalty this is in the same PR as #54, sorry @MathiasPaumgarten for that). 

Instead of default resolving the left part

```JS
var contentValue = resolveName( left, values );
```

we can check if the variable is present in the `values` hash and resolve it:

```JS
if( mout.object.has( values, left ) ) left = resolveName( left, values );
if( mout.object.has( values, right ) ) right = resolveName( right, values );
```

Have run all tests and had no fails.

**Comment by MathiasPaumgarten** [comment]
I have merged that in as well with you last PR.
