### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by hudochenkov** [MathiasPaumgarten/grunt-bake#61]
Please, start to write changelog.

**Comment by MathiasPaumgarten** [comment]
Good point. Going forward I shall keep a change log in the README.

**Comment by MathiasPaumgarten** [comment]
I'll added one with the most recent feature. It would require a lot of digging through the past to make a changelog for everything. But I'll keep it up.

**Comment by hudochenkov** [comment]
Thank you!
