### ISSUE TITLE
Parsing fails when inline section contains symbols only

### ISSUE THREAD

**Issue by david-zacharias** [MathiasPaumgarten/grunt-bake#63]
Regular expression in bake does not detect inline sections like:

```HTML
<!--(bake-start _if="!item@last")--> | <!--(bake-end)-->
```

Workaround is to add some characters like:

```HTML
<!--(bake-start _if="!item@last")-->&nbsp;|&nbsp;<!--(bake-end)-->
```

**Comment by MathiasPaumgarten** [comment]
Nice catch. I'll take a look.

**Comment by MathiasPaumgarten** [comment]
I had a a `|` in the regex, by which I meant `or` but it took it literally. Removed that, as it isn't necessary within the `[ ]` group.

**Comment by MathiasPaumgarten** [comment]
New version `1.2.1` fixes that.

**Comment by david-zacharias** [comment]
Have tested version `1.2.1` in the project where I stumbled upon the issue and can approve that your fix works :+1: Thanks!
