### ISSUE TITLE
Usage of variable in filename

### ISSUE THREAD

**Issue by MichelGratton** [MathiasPaumgarten/grunt-bake#64]
I guy's,

In version 0.3.16, I was using code like this:
`<\!--(bake /sources/pages/static-sample-contents/{{tab.content}}.html)-->`

Yesterday, I update to the latest version of bake to have access to all new properties and fix. But my bake include doesn't work anymore because it bake doesn't parse the file name before testing if the file exists.
Error is ; Warning: Unable to read "sources/pages/static-sample-contents/{{tab.content}}.html" file (Error code: ENOENT). Use --force to continue.

**Comment by david-zacharias** [comment]
Hm, did not know that bake processed variables in include names. But it should not be that difficult to add support for this.

Can you please provide a complete code example of your template?

**Comment by MichelGratton** [comment]
Just edited my post

**Comment by MichelGratton** [comment]
With more details information:

JSON content: 
`{
	"tabs": [
		{
			"id": "sample-tab-content1",
			"title": "Tab title 1",
			"content": "tabs-component-content-1"
		},
		{
			"id": "sample-tab-content2",
			"title": "Tab title 2",
			"content": "tabs-component-content-2"
		},
		{
			"id": "sample-tab-content3",
			"title": "Tab title 3",
			"content": "tabs-component-content-3"
		},
		{
			"id": "sample-tab-content4",
			"title": "Tab title 4",
			"content": "tabs-component-content-4"
		}
	]
}`

code: `<!--(bake components/tabs.html _section="sample-tabs")-->`
tabs.html:
`<div class="fn-tabs">
	<nav>
		
		<a href="#{{tab.id}}">{{tab.title}}</a>
		
	</nav>
	
		<div id="{{tab.id}}" class="tab-content">
		
		</div>
	
</div>`

Is this help ?

**Comment by david-zacharias** [comment]
Thanks for the code example. I have added support for placeholders within include paths to the master branch. 

@MichelGratton please check if this code works for you by using the current master (`npm install git+https://github.com/MathiasPaumgarten/grunt-bake.git`). 

@MathiasPaumgarten The honor of bumping the version and starting a changelog belongs to you :wink:

**Comment by MichelGratton** [comment]
Thank you very much, I will try this right away :)

**Comment by MathiasPaumgarten** [comment]
Hey guys. I'm also surprised that it did work before. I never really anticipated for it. It must be because of how `grunt-bake` used to parse inline and external bakes. Thanks to a long needed refactor, this accidental side effect (bug, I might say) was closed. 

However, it's now officially supported thanks to @david-zacharias. I'm in the process of reviewing and merging. I'll post another update in a few minutes.

**Comment by MathiasPaumgarten** [comment]
Alright guys. This is now a supported feature. File paths are parsed as well. 
@MichelGratton you can update to `1.3.0` and it will include that feature. Excited to see `grunt-bake` thrive under the careful attention of @david-zacharias. :cool: :high_brightness:

**Comment by MichelGratton** [comment]
Works fine :) Very happy.

**Comment by david-zacharias** [comment]
I am very pleased to hear that :+1:  Thanks @MathiasPaumgarten for bringing the changes live so quickly!

**Comment by k-funk** [comment]
Updated to 1.3.0 from 0.3.18 and had the OP's error, though my example is a little more complex.
`Warning: Unable to read "../includes/{{book1.filename}}" file (Error code: ENOENT). Use --force to continue.`

**pages/book_page_1.html**

    

**includes/book_sidebar.html**

    

**content.json**

    {
        "book1": {
            "img": "../includes/book_sidebar_partial.html"
        },
    }

**Comment by david-zacharias** [comment]
Hi @k-funk, thanks for your feedback!

The resulting errors are similar to previous reported problem, but the issue here is that inline values are not processed by `defaultProcess`, so placeholders are not resolved. In bake 0.3.x also bake code was (unintentionally) processed. 

I have moved your report into a new issue #67.
