### ISSUE TITLE
Lint error caused by regex

### ISSUE THREAD

**Issue by david-zacharias** [MathiasPaumgarten/grunt-bake#65]
The main regex for parsing bake tags causes following jshint error:

```SHELL
[L110:C64] Unescaped '^'.
    var regex = /(\n?)([ \t]*)<!--\(\s?bake(-start|-end)?([^]*?)\)-->/;
```

I think we can change the `[^]` part to `[\s\S]` which also covers *everything*, but does not cause a linting error. Tests run green with that change. I will leave final decision to you, @MathiasPaumgarten.

**Comment by MathiasPaumgarten** [comment]
Absolutely. This is much nicer, and way less cryptic.
