### ISSUE TITLE
Error on empty bake-tag

### ISSUE THREAD

**Issue by david-zacharias** [MathiasPaumgarten/grunt-bake#66]
Stumbled upon this today, nothing major but should be fixed sometime. 

**Template**
```HTML
<!--(bake-start _if="somevar")-->
<!--(bake-end)-->
```

**Error reported in shell**
```
Warning: Unable to read "src/includes/" file (Error code: EISDIR). Use --force to continue.
```

**Comment by david-zacharias** [comment]
@MathiasPaumgarten And this is fixed as well... was only one missing `if`

**Comment by MathiasPaumgarten** [comment]
Nice. You back on a fixing spree ... :raised_hands:
