### ISSUE TITLE
Resolve placeholders within inline-vars

### ISSUE THREAD

**Issue by david-zacharias** [MathiasPaumgarten/grunt-bake#67]
As pointed out by @k-funk in #64, bake does not process placeholders within inline values since 1.x. 

Copy of report from k-funk:
----

Updated to 1.3.0 from 0.3.18 and had the OP's error, though my example is a little more complex.
`Warning: Unable to read "../partials/{{book1.partialPath}}" file (Error code: ENOENT). Use --force to continue.`

**pages/book_page_1.html**

    

**includes/book_sidebar.html**

    

**content.json**

    {
        "book1": {
            "bookPartial": "../partials/book_sidebar_partial.html"
        },
    }

I [included a unit test on a branch](https://github.com/k-funk/grunt-bake/tree/recursive_placeholders) so you can see the error yourself.

**Comment by david-zacharias** [comment]
**Update**
It is true that bake does not process placeholders in inline values, but when these are afterwards used within the content like `<li>{{bookPartial}}</li>` the later parsing of the sub-section resolves the placeholder, so this behavior was not noticed. If the inline-var is used within a subsequent bake-tag e.g. `<!--(bake {{bookPartial}})-->` bake fails because these are not resolved.

**Comment by david-zacharias** [comment]
I have merged your test case and added support for resolving placeholders within inline-vars to the master branch. 

@k-funk please check if this code works for you by using the current master (`npm install git+https://github.com/MathiasPaumgarten/grunt-bake.git`). Please note that I changed the path in `include-three.html` because paths are relative to the templates location, hence `include/` was surplus.

@MathiasPaumgarten please check if you agree with the small extension :bow:

**Comment by k-funk** [comment]
Fixed for me. Thanks @david-zacharias! Looking forward to the 1.3.1.

**Comment by MathiasPaumgarten** [comment]
Hey guys, as always, David has fixed everything before I even had a chance to look at it. Clean fix as always. Gonna bump and push now.

**Comment by MathiasPaumgarten** [comment]
Pushed @david-zacharias's feature to npm: `1.3.1`

Thanks guys, high fives all around. (Mostly between you two) :hand:

**Comment by hiulit** [comment]
Hi there!

So I have an `index.html` like this:

```html
<ul>
    <!--(bake-start _foreach="prova:proves" _bake="includes/tutorial-base.html > {{prova.id}}/{{prova.id}}.html")-->
    <li>
        <a href="./pages/proves/{{@link}}">{{prova.title}}</a>
    </li>
    <!--(bake-end)-->
</ul>
```

with a `json`like this:

```json
{
  "proves": [
    {
      "id": "hola",
      "title": "Hola",
      "metas": {
        "url": "hola",
        "title": "Hola",
        "description": "Hola",
        "meta-keywords": "hola"
      }
    }
  ]
}
```

and the `tutorial-base-html` like this:

```html
<h1>{{prova.title}}</h1>
{{prova.id}}
<!--(bake ../{{prova.id}}/{{prova.id}}.html)-->
```

and I'm getting this error:

```bash
Warning: Unable to read "app/pages/proves/includes/..//.html" file (Error code: ENOENT).
```

It seems that it doesn't like placeholders inside `_bake` html 'detail' template:

Does this have something to do with this thread?

Thanks!

**Comment by david-zacharias** [comment]
Hi @hiulit, happy to see that you are using bake! 

I think the error is caused by `<!--(bake ../{{prova.id}}/{{prova.id}}.html)-->` in the `tutotial-base.html`. The default bake include path does not support placeholders, since you *know* which (static) files you want to bake together. The `_bake`-option supports placeholders for generating the names for the files bake should create.

So this behavior is not related resolving placeholders within inline-vars.

What is your intent of the `<!--(bake ../{{prova.id}}/{{prova.id}}.html)-->` inside the `tutotial-base.html`?

**Comment by hiulit** [comment]
Hi @david-zacharias 

Sorry, I'll elaborate my question in more depth.
What I want to accomplish is this:

I have a folder structure resembling to this:

```bash
tutorials
├── advanced
│   ├── advanced-1.html
│   ├── advanced-2.html
│   └──  advanced-3.html
├── basic
│   ├── basic-1.html
│   ├── basic-2.html
│   └── basic-3.html
├── index.html
└── quick-start
    ├── quick-start-1.html
    ├── quick-start-2.html
    └── quick-start-3.html
```

And this an example `json`:

```json
"tutorials": [
  {
    "id": "home",
    "title": "Tutorials",
    "metas": {
      "url": "tutorials",
      "title": "Tutorials",
      "description": "some description",
    },
    "items": []
  },
  {
    "id": "quick-start",
    "title": "Quick start",
    "metas": {
      "url": "tutorials/quick-start",
      "title": "Quick start - Tutorials",
      "description": "some description",
    },
    "items": [
      {
        "id": "quick-start-1",
        "title": "Quick start 1",
        "metas": {
          "url": "tutorials/quick-start/quick-start",
          "title": "Quick start 1 - Tutorials",
          "description": "some description",
        }
      }
    ]
  }
]
```

Each individual tutorial html (e.g. `quick-start-1.html`) has its own content that I want to bake using the `tutorial-base.html` template.

```html
<p>I'm the content from {{tutorial.title}}</p>
```

Now, I have a `tutorial-base.html` template in another folder called `includes` along with some others, such as `header.html, `footer.html`, etc.

```html
<!--(bake /includes/header.html)-->
<section class="tutorials-section">
    <div class="wrapper">
        <h1>{{prova.title}}</h1>
        {{prova.id}}
        <!--(bake ../{{tutorial.id}}/{{tutorial.id}}.html)-->
    </div>
</section>
<!--(bake /includes/footer.html)-->
```

Ans finally I have an `index.html`, like this:

```html
<!--(bake /includes/header.html _section="pages.tutorials")-->
<section class="tutorials-section">
    <div class="wrapper">
        <ul>
            <!--(bake-start _foreach="tutorial:tutorials" _bake="/includes/tutorial-base.html > {{tutorial.id}}/{{tutorial.id}}.html")-->
            <li>
                <a href="./pages/tutorials/{{@link}}">{{tutorials.title}}</a>
<!--(bake-start _if="tutorial.items")-->
                <ul>
                    <!--(bake-start _foreach="item:tutorial.items" _bake="includes/tutorial-base.html > {{item.id}}/{{item.id}}.html")-->
                    <li>
                        <a href="./pages/tutorials/{{@link}}">{{item.title}}</a>
                    </li>
                    <!--(bake-end)-->
                </ul>
                <!--(bake-end)-->
            </li>
            <!--(bake-end)-->
        </ul>
    </div>
</section>
<!--(bake /includes/footer.html)-->
```
It creates a menu of all the tutorials and also creates each individual tutorial within its own folder. And it works perfectly as long as I "hardcode" tutorial id `<!--(bake ../quick-start-1/quick-start-1.html)-->` in the `template-basic.html`.

What I want is to be able to bake all the individual tutorials with its own content dynamically using the `template-basic.html` and passing the `tutorial.id`.

Does this make sense to you?

**Comment by hiulit** [comment]
I'm back!

I don't know if my gigantic comment was of any use, but I think I fixed the issue (at least for my case :P).

Line 440 of  `bake.json` inside the `processExtraBake` function:

```js
      var dest = preparePath( bake.dest, destFile, values );
```
```js
      var dest = preparePath( processContent( bake.dest, values ), destFile, values );
```

I just passed `bake.dest` through `processContent` and it seems to be working, whether you use a 'hardcoded' name or a 'placeholder'.

I don't know if this would be something useful  to anybody or maybe to add it to master... Any comments on that?

**Comment by david-zacharias** [comment]
Sorry have a lot of work on my desk. Will check your detailed explanation as soon as I find time. Improvements to bake are always welcome. Feel free to create a Pull Request. Please do not forget to run the tests to be sure that your additions do not break existing functionality. Also adding a test for your addition is great, so it won't be removed in future updates.
