### ISSUE TITLE
Support for complex if-conditions

### ISSUE THREAD

**Issue by david-zacharias** [MathiasPaumgarten/grunt-bake#69]
Hey!

For some situations it would be handy to use more complex if-conditions like:

```HTML
<!--(bake-start _foreach="item:[One, Two, Three]")-->
    {{item}} <!--(bake-start _if="item@index%2"--> it's odd <!--(bake-end)-->
<!--(bake-end)-->
```
or even:

```HTML
<!--(bake-start _foreach="item:[1, 2, 3, 4, 5]")-->
    <!--(bake-start _if="item <= max"-->{{item}}<!--(bake-end)-->
<!--(bake-end)-->
```

I thought about how to integrate support for this into grunt-bake. In my opinion this is a useful case for `eval`. Since this is where opinions differ (saying eval is evil, B.A.D, etc.) I would like to discuss first. 

My current idea is to change the `validateIf` to:

```JS
// expression used to search for placeholder / variables within an if-condition
var ifRegex = /([a-z_$][0-9a-z_$@]*)|(?:"([^"]*)")|(?:'([^']*)')/gi;

function validateIf( inlineValues, values ) {

	if ( "_if" in inlineValues ) {

		var value = inlineValues[ "_if" ];
		delete inlineValues[ "_if" ];

		var params = {};
		
		var condition = value.replace( ifRegex, function( match, varname ) {
			if( ! varname ) return match;
			// save resolved spaceholders values for later use by eval()
			params[ varname ] = resolveName( varname, values );
			// prefix all placeholders/variables to prevent access to grunt scope
			return "params." + varname;
		});

		return ! eval( condition );
	}

	return false;
}
```

I do the prefixing because this way (as far as I see for now) it is not possible to manipulate the if-condition from the JSON-content. As the JSON may comes from user generated (= unsecure) sources I would like to prevent this. Within the template it is possible to add javascript code, but as the template is in (trusted) developer hands, I do not see danger here or in other words danger is as high as code in Gruntfile or other js-files.

Changing to eval would make some other methods obsolete e.g. `isFalse`. The code above does not support *semantic if* currently, but that can be added.

So, ideas, remarks, recommendations? @MathiasPaumgarten what do you think?

**Comment by MathiasPaumgarten** [comment]
Hey there. The implementation is clean, for sure. And I like the idea. I was just trying to think of a somewhat clean way that allows us to not use `eval()`.
Don't get me wrong, I'm with you on the reasoning as well. This is code that gets executed locally, and it only gets fed what you write yourself, so there isn't many safer circumstances than those. 

I'm pretty sure I could be persuaded to add this, as it adds really nice upsides. Would you mind making a PR for something this size. We would also have to make sure it adds __semantic-if__ support. Can't kick that out now. Personally I don't use it, but I don't have any stats on how many people do. And it was a nice contribution.

**Comment by david-zacharias** [comment]
I am totally with you regarding the `eval()`, I also thought about ways to omit it.  But finally came to conclusion that it would be code to write (also kind of redundant because it implements behavior already existing in javascript) or conditions will be limited in complexity and support for operators.

I will come up with a full implementation (compatible with current bake, including **semantic-if**) as soon as I find time and create a PR. Till then you may take a look at my PR #68 for baking extra files.
