### ISSUE TITLE
_if fails when placeholders reference object attributes

### ISSUE THREAD

**Issue by david-zacharias** [MathiasPaumgarten/grunt-bake#72]
The *escaping* mechanism in the new `validateIf`-implementation fails when placeholder references object attributes. like:

```
<!--(bake-start _if="info.author")-->
```

I will take care of fixing this.

**Comment by david-zacharias** [comment]
@MathiasPaumgarten I have pushed the fix directly into the master as it only affects two lines. Commit is referenced. Can you please bump the version so it becomes available via npm?

**Comment by MathiasPaumgarten** [comment]
Oh man. Thanks. Weird that no test caught that :/

**Comment by MathiasPaumgarten** [comment]
:ship:  `v1.4.1`

**Comment by david-zacharias** [comment]
True, true, I was also surprised. Now we have a test in place. Thanks for the instant release.
