### ISSUE TITLE
Add variable for linking to originating file when using _bake-attribute

### ISSUE THREAD

**Issue by david-zacharias** [MathiasPaumgarten/grunt-bake#74]
As a little addition I would like to inject a variable `@referrer` to be able to link from dynamically generated files back to the originating file. This is handy when one uses `_bake`-attributes with same *detail-template* in multiple files (e.g. `detail-member.html` used in `index.html` and `team.html`, so return link is in one case `index.html` in the other `team.html`).

**Comment by david-zacharias** [comment]
@MathiasPaumgarten As this was a minor change in a *submodule* I have added it directly to master.

**Comment by MathiasPaumgarten** [comment]
Just pushed this to `1.5.1`. Looking through #71 now.
