### ISSUE TITLE
Can't access properties in _section

### ISSUE THREAD

**Issue by k-funk** [MathiasPaumgarten/grunt-bake#80]
I expected this to already be working, since I can access object properties in an _if (`_if="book.title == 'The Dark Tower'"`), but it appears to not work on _section.

I've created a pull request with only a unit test: https://github.com/MathiasPaumgarten/grunt-bake/pull/79

**Comment by MathiasPaumgarten** [comment]
This has been taken care of in #79 and 26566f1f8acf569923594526c5d40915bfc84cc9
