### ISSUE TITLE
JSON file or CSV convert to multiple HTML files

### ISSUE THREAD

**Issue by webnet2** [MathiasPaumgarten/grunt-bake#83]
Can someone please show me how to generate a JSON or CSV file to multiple HTML files? Basically, I'm looking for each JSON object to be converted into a single HTML page (so if there are 50 objects then I will have 50 HTML files). Or each row into a single HTML file. I tried different scenarios but no luck.

**Comment by david-zacharias** [comment]
So you have an array of objects in your JSON data, right? I guess so.

Do you also want to have one *main file* that links to the generated files? 

If yes, you can use the [_bake](https://github.com/MathiasPaumgarten/grunt-bake#bake-extra-pages-eg-detail-pages)-attribute for generating extra files from within the `_foreach`-loop in your *main file* for each object.

If not, you need to run bake for each file. Which is possible with the Grund-files syntax. The problem I see and you probably stumbled upon is how to tell bake which object to use for each file. Currently I see no way to do this, sorry. Maybe @MathiasPaumgarten can come up with a hack that will do the trick.

**Comment by david-zacharias** [comment]
How does your code look?

**Comment by webnet2** [comment]
I only tried to run the Simple bake to be sure it will generate a couple of html pages but it did not seem to work on my node.js - Here is the simple bake [click here](https://github.com/MathiasPaumgarten/grunt-bake#simple-bake)

**Comment by david-zacharias** [comment]
Without more information about your specific settings I can not provide more help. Simple bake (and all other features) run on my local configuration as well as on travis CI.

**Comment by webnet2** [comment]
I have not tried the bake before so that is why I couldn't make the simple one work. I think bake is the solution that I'm looking for so I need your help. I have a CSV file with say 50 rows or objects (json) and I need it to generate it to 50 html pages (per row/object).

**Comment by webnet2** [comment]
I tried to run bake_test.js but seemed to be nothing happened - I followed the test. What did I miss?
![bake_test](https://cloud.githubusercontent.com/assets/18010579/14183185/acc4fd48-f723-11e5-8cb5-19506d780705.png)

**Comment by webnet2** [comment]
I tried to run bake but it seemed like nothing happened. I need help...
![bake_test](https://cloud.githubusercontent.com/assets/18010579/14185471/d84b395e-f72e-11e5-88f1-d8ba54d4a52a.png)

**Comment by david-zacharias** [comment]
I get the feeling that you missed to read the basics of Grunt. So please take time to read the [Getting Started guide](http://gruntjs.com/getting-started). I will close your issue for now because it is not a feature request or bug report related to this project. Probably [stackoverflow](http://stackoverflow.com/) the better place to get help. But first, please read the guide.

**Comment by webnet2** [comment]
Okay. I got it working now! Thanks! :-)

**Comment by MathiasPaumgarten** [comment]
Glad you guys could hash it out. As always @david-zacharias thanks for being so on top on responding to user issues.
