### ISSUE TITLE
foreach loop to build multiple files per object

### ISSUE THREAD

**Issue by webnet2** [MathiasPaumgarten/grunt-bake#85]
Looking for a way to loop this for each object and have its own generated page. Any suggestion please? I was looking at [grunt.file.expandMapping](grunt.file.expandMapping)
![foreachloop](https://cloud.githubusercontent.com/assets/18010579/14192669/f3c275c4-f753-11e5-85b8-79ef3e4b028b.png)

**Comment by david-zacharias** [comment]
Hi @webnet2 I am happy that you chose grunt-bake for your project! Neverthelesse, the issues at github exist for reporting and discussing bugs and features, they are not meant for requesting support for individual programming challenges. As written in my comment on [issue 83](https://github.com/MathiasPaumgarten/grunt-bake/issues/83) bake may is not made for what you want to do, but can create individual files by the use of [_bake](https://github.com/MathiasPaumgarten/grunt-bake#bake-extra-pages-eg-detail-pages)-attribute. Please do more research and make use of knowledge bases like [stackoverflow](http://stackoverflow.com/). Thanks!
