### ISSUE TITLE
Unset variables are rendered as "undefined"

### ISSUE THREAD

**Issue by david-zacharias** [MathiasPaumgarten/grunt-bake#86]
This also happens when `removeUndefined` is set to `true`.

**Comment by david-zacharias** [comment]
I have quickly added a fix for this issue. @MathiasPaumgarten can you please bump the version when you have the time.

**Comment by MathiasPaumgarten** [comment]
Sure can.

**Comment by MathiasPaumgarten** [comment]
I have pushed `1.6.4`. I should check if I can give you publish rights on npm for situations like this one.
