### ISSUE TITLE
Assign/use variable in same file

### ISSUE THREAD

**Issue by k-funk** [MathiasPaumgarten/grunt-bake#90]
Is it possible to do this?

**file.html**

```
(define a var like pageTitle="Bakeware")
<h1>{{pageTitle}}</h1>
<p>Here we are in the {{pageTitle}} page.</p>
<!--(bake more_details.html pageTitle={{pageTitle}})-->
```

**more_details.html**

```
Even more details about {{pageTitle}} here.
```

**Comment by david-zacharias** [comment]
Currently not because each bake tag "must" include a file. There is no bake tag dedicated just to assign variables / placeholders. So it would be a major change (from point of concept) to allow this.
