### ISSUE TITLE
Builtin placeholders

### ISSUE THREAD

**Issue by nabto** [MathiasPaumgarten/grunt-bake#92]
Have worked with other "template" engines like bake before.

Something that is nice is to have in templating languages is builtin placeholders.

What is currently needed in a project is the current_filename - we can do this manually in the top of each file ... but it's tedious.. and good programmers are born lazy.. (my personal belief is that most programmers start their career because it would be nice to create/program a robot that cleans up their room - so they dont have to)
But other builtin placeholders could also be nice like date and time.
Possible user and machine (uname like etc.)
Possible grunt version (and other software versions) so its possible to "stamp" generated files for later tracking.

**Comment by MathiasPaumgarten** [comment]
Hi there. That is pretty good input. I like that. I have to admit it's been a while that I have worked on __grunt-bake__. Because, as you said, we're all lazy 😄 
I think this wouldn't even require too much of a change. Let me look into it.

**Comment by MathiasPaumgarten** [comment]
Closing this in lieu of #93
