### ISSUE TITLE
Generate Bake with grunt.config.get

### ISSUE THREAD

**Issue by tnqsoft** [MathiasPaumgarten/grunt-bake#95]
Hi !

How can generate bake with "grunt.config.get"?. Example:
includes/header.html
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="<%= grunt.config.get('pkg.description') %>">
    <meta name="keywords" content="<%= grunt.config.get('pkg.keywords') %>">
    <meta name="author" content="<%= grunt.config.get('pkg.author.name') %>">
    <link rel="icon" href="img/favicon.ico">
    <title><%= grunt.config.get('pkg.name') %></title>
   ..........
```

pages/home.html
```
<!--(bake ../includes/header.html)-->

<div class="page-header">
```

But when page generate by Bake, I saw in file content "home.html" contain <%= grunt.config.get('pkg.description') %>...I wanna Bake call grunt.config.get for get parameter value. I find solution in internet, and I found solution:

```
bake: {
    build: {
        options: {
            content: "<%= sourceDir %>/data/content.json",
            section: "en",
            process: function (content, srcpath) {
                 return grunt.template.process(content);
            }
        },
        files: [{
```

I resolve problem with grunt.config.get, but I have problem with options.content, it mean Bake can not generate page with content.json. File after build keep key of content file instead of value like.  {{example.title}}

Help me please!. Sorry with my English!.

**Comment by david-zacharias** [comment]
Hi again,

generally I suggest not to overwrite the `process`-function, because you loose bake-functionality. But you can mix the configuration into your content object; [options.content](https://github.com/MathiasPaumgarten/grunt-bake#optionscontent) can also be a callback, so you can do something like:

```JS
bake: {
	build: {
		options: {
			content: function() {				
				var file = grunt.config.get('baseProject.data') + '/data/content.json';
				var content = grunt.file.readJSON(file);

				content['conf'] = grunt.config.get('pkg');

				return content;
			}
		}
		// ... files ...
	}
}
```

In the template you can access the variables like other content:

```HTML
    <meta name="description" content="{{conf.description}}">
```

**Comment by tnqsoft** [comment]
Amazing and Perfect!! I really like you!. Save my time.

I update Gruntfile.js for Bake.

```
bake: {
    build: {
        options: {
            content: function() {
                var file = grunt.config.get('sourceDir') + '/data/content.json';
                var content = grunt.file.readJSON(file);

                content['conf'] = grunt.config.get('pkg');
                content['vendorDir'] = grunt.config.get('vendorDir');

                return content;
            }
        },
...
```

Thank you so much!!!!!.
