### ISSUE TITLE
Bake one HTML file / JSON section in one go

### ISSUE THREAD

**Issue by jroland01** [MathiasPaumgarten/grunt-bake#96]
Hi -

I have a JSON file (e.g. content.json) with several sections (e.g. section1, section2, etc.) and I am trying to bake 1 HTML file per section in this JSON file. Is there a way to go through all sections in the JSON file in one go and bake the HTML files accordingly ?  

Currently I am doing this “manually” in Gruntfile.js for each section (e.g. for section2) in the JSON file :

```js
build: { 
	options: {
		content: 'content.json',
		section: 'section2'
	},
	files: {
		'section2/index.html': 'template.html'
	}
}
 ```

Is this possible ? If not is there a workaround so that I don’t have to add a new block of code in Gruntfile.js each time I am adding a section ?

Thanks a lot.

**Comment by david-zacharias** [comment]
Hey!

Have you taken a look the [bake extra pages](https://github.com/MathiasPaumgarten/grunt-bake#bake-extra-pages-eg-detail-pages) section? I think that should work for your use case.

Please let me know if you could apply this to your project.

**Comment by jroland01** [comment]
Hi - Thanks a lot for your reply.

I could potentially apply that. The thing is, the JSON I am using is structured according to "sections", and not as an array. My understanding is that the _foreach statement in bake extra pages goes through items in an array, not through "sections". So I would require the same feature as in bake extra pages, but with the ability to go through "sections" instead of items in an array (e.g. a "mix" of _foreach and _section statement features). 

Just to give you some background : I am using grunt-frontmatter to extract frontmatter from a list of markdown files, and it generates that JSON file with filenames as "sections" (so I have little control over how it is structured) :

{
  “filename1”: {
    "language": “fr”,
    "name": “name1”,
    "description": “description1” 
  },
  “filename2”: {
    "language": "fr",
    "name": “name2”,
    "description": “description2” 
  },
...
} 

What do you think ? Thanks a lot in advance !

**Comment by david-zacharias** [comment]
If the data you have is not matching the requirements `grunt-bake` has, you can transform the data by using a function for `options.content`:

```js
options: {
    content: function() {
        var file = './data/content.json';
        var content = grunt.file.readJSON(file);

        return _.values(content); // e.g. http://underscorejs.org/#values
    }
},
```

You could also do some sorting and mixin the keys (`filename1`, `filename2`, ...) as a property so they become available in the templates:

```js
return _.chain(content)
	.mapObject(function (section, filename) {
		return _.extend({}, section, {
			filename: filename
		});
	})
	.values()
	.sortBy('name')
	.value();
```

**Comment by jroland01** [comment]
Thanks a lot ! I will look into your suggestions. Alternatively I will input my data directly in the required format for `grunt-bake` / bake extra pages.

**Comment by david-zacharias** [comment]
Hope you found a suitable solution. I will close this issue, since it is not a feature or bug. But I will create one feature issue for supporting iteration over objects in `_foreach`
