### ISSUE TITLE
Iteration over objects in _foreach

### ISSUE THREAD

**Issue by david-zacharias** [MathiasPaumgarten/grunt-bake#97]
Bake should may support iteration over objects in `_foreach`. In this case the key should also be supplied in the template.

### Example (WIP)

_Configuration_
```js
 options: {
	content: {
		project: {
			name: 'Hello World',
			owner: 'John Doe',
			licence: 'MIT'
		}
	}
}
````

_Template_
```html
<dl>
<!--(bake-start _foreach="val:project")-->
  <dt>{{val@key}}</dt>
  <dd>{{val}}</dd>
<!--(bake-end)-->
</dl>
```

_Output_
```html
<dl>
  <dt>name</dt>
  <dd>Hello World</dd>
  <dt>owner</dt>
  <dd>John Doe</dd>
  <dt>licence</dt>
  <dd>MIT</dd>
</dl>
```

**Comment by jroland01** [comment]
This feature would be very useful. Thanks.

**Comment by MathiasPaumgarten** [comment]
I think this is great. Should we maybe find a syntax that specifies both `key` and `value`? Not a must, just thinking out loud:

```html
<dl>
<!--(bake-start _foreach="key:value:project")-->
  <dt>{{key}}</dt>
  <dd>{{value}}</dd>
<!--(bake-end)-->
</dl>
```

Since this could still work with arrays since the key of every array field is simply a number. (I don't want to offend any real computer scientists here but my point is that in JS it sure seems/feels that way 😄 )

What do you guys think?

Either way, we should definitely support this.

**Comment by david-zacharias** [comment]
Would be nice to have a inline syntax. Are the _many_ colon separated parts confusing? We could also think about introducing alternative foreach syntax in __2.0__ like (of course with support for __1.x__ colon-syntax).

```js
_foreach="projects as key => value" 
```

Not sure.

**Comment by MathiasPaumgarten** [comment]
Yeah I agree. I feel like the whole colon thing is something I started when there was pretty much no command and now it's totally out of proportion. 
(I'm pretty sure this is how Brandon Eich feels about JavaScript every day)

**Comment by MathiasPaumgarten** [comment]
I'm probably gonna spend some time on this today, as well as #93

**Comment by MathiasPaumgarten** [comment]
Closing this because I started a PR #98 and we should discuss it there.
